# Generated by Django 4.2.2 on 2023-06-24 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argomento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('materia', models.CharField(max_length=128)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='utente',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='utente',
            name='username',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Videogioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_breve', models.CharField(max_length=160)),
                ('descrizione', models.TextField()),
                ('monete', models.IntegerField()),
                ('immagini_1', models.URLField()),
                ('immagini_2', models.URLField()),
                ('immagini_3', models.URLField()),
                ('argomento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.argomento')),
            ],
        ),
        migrations.CreateModel(
            name='SvolgeGioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monete', models.IntegerField(null=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.classe')),
                ('gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.videogioco')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.utente')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=160)),
                ('gioco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.videogioco')),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edu.utente')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='catalogo',
            field=models.ManyToManyField(to='edu.videogioco'),
        ),
        migrations.AddField(
            model_name='classe',
            name='creata_da',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classe_creator', to='edu.utente'),
        ),
        migrations.AddField(
            model_name='classe',
            name='iscrizione',
            field=models.ManyToManyField(to='edu.utente'),
        ),
        migrations.AddField(
            model_name='utente',
            name='svolge',
            field=models.ManyToManyField(through='edu.SvolgeGioco', to='edu.videogioco'),
        ),
        migrations.AddField(
            model_name='utente',
            name='valuta',
            field=models.ManyToManyField(related_name='utente_feedback', through='edu.Feedback', to='edu.videogioco'),
        ),
    ]
