# Generated by Django 4.2.2 on 2023-06-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0002_argomento_classe_alter_utente_mail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argomento',
            name='descrizione',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='catalogo',
            field=models.ManyToManyField(blank=True, to='edu.videogioco'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='iscrizione',
            field=models.ManyToManyField(blank=True, to='edu.utente'),
        ),
    ]
