# Generated by Django 4.2.2 on 2023-06-24 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0003_alter_argomento_descrizione_alter_classe_catalogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_1',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_2',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_3',
            field=models.URLField(null=True),
        ),
    ]
