# Generated by Django 4.2.2 on 2023-06-24 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edu', '0004_alter_videogioco_immagini_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_1',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_2',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='videogioco',
            name='immagini_3',
            field=models.URLField(blank=True, default=''),
        ),
    ]
